if(NOT DEFINED INPUT_FILE OR NOT DEFINED OUTPUT_FILE OR NOT DEFINED SYMBOL_NAME)
    message(FATAL_ERROR "INPUT_FILE, OUTPUT_FILE, and SYMBOL_NAME are required")
endif()

file(READ "${INPUT_FILE}" shader_hex HEX)
string(LENGTH "${shader_hex}" shader_hex_length)
math(EXPR trailing_bytes "${shader_hex_length} % 8")
if(NOT trailing_bytes EQUAL 0)
    message(FATAL_ERROR "SPIR-V input size is not a multiple of four bytes")
endif()

math(EXPR word_count "${shader_hex_length} / 8")
math(EXPR last_word "${word_count} - 1")
set(shader_words "")

foreach(word_index RANGE 0 ${last_word})
    math(EXPR offset "${word_index} * 8")
    string(SUBSTRING "${shader_hex}" ${offset} 2 byte0)
    math(EXPR offset1 "${offset} + 2")
    math(EXPR offset2 "${offset} + 4")
    math(EXPR offset3 "${offset} + 6")
    string(SUBSTRING "${shader_hex}" ${offset1} 2 byte1)
    string(SUBSTRING "${shader_hex}" ${offset2} 2 byte2)
    string(SUBSTRING "${shader_hex}" ${offset3} 2 byte3)
    string(APPEND shader_words "    0x${byte3}${byte2}${byte1}${byte0}u,\n")
endforeach()

set(header "#pragma once\n\n#include <array>\n#include <cstdint>\n\n")
string(APPEND header "inline constexpr std::array<std::uint32_t, ${word_count}> ${SYMBOL_NAME} = {\n")
string(APPEND header "${shader_words}};\n")
file(WRITE "${OUTPUT_FILE}" "${header}")
